### ISSUE TITLE
Actual use case

### ISSUE THREAD

**Issue by JLLeitschuh** [TQRG/secom#2]
I'm using the secom standard in my work as a security researcher. I find and fix widespread common security vulnerabilities across Open Source by generating hundreds of PRs to fix vulnerabilities at scale.

You can see the two campaigns I've run so far using this standard for the commit message:
 - https://github.com/JLLeitschuh/security-research/issues/9
 - https://github.com/JLLeitschuh/security-research/issues/8

**Comment by sofiaoreis** [comment]
Cool! Thanks for sharing these use cases. Can we use them in our future presentations? We will release a linter soon.

**Comment by JLLeitschuh** [comment]
Go for it. I'll be presenting this bulk PR generation work at DEFCON, Black Hat, and BSides LV. If I have enough time, I'll mention this project in that presentation

**Comment by sofiaoreis** [comment]
Thanks! Good luck with your presentation at DEFCON!!

**Comment by JLLeitschuh** [comment]
This did get briefly mentioned at DEF CON and Black Hat in my talk titled "Scaling the Security Researcher to Eliminate OSS Security Vulnerabilities Once and For All"
https://youtu.be/UgGhEfdUSvQ

**Comment by sofiaoreis** [comment]
Thanks for sharing the work in your different talks! Would you mind if I add references to the talks in our website?

**Comment by JLLeitschuh** [comment]
Sorry for never responding. Go for it!
