### ISSUE TITLE
Use in Proposed Specification

### ISSUE THREAD

**Issue by JLLeitschuh** [TQRG/secom#3]
I'm proposing that this commit format be the standard for all automated future pull request campaigns.

Feel free to take a look:
https://docs.google.com/document/d/1_QwN7yQXWGM2tJaostIRNqyZIhVceVlIyXqCrSdC4E8/edit

**Comment by sofiaoreis** [comment]
Cool! Thanks for doing this. Would you like me to add any extra information to the doc? (I see you added a link to SECOM's website, is it enough?)

**Comment by JLLeitschuh** [comment]
> Would you like me to add any extra information to the doc?

Not unless you have any suggestions/feedback on the proposal
