### ISSUE TITLE
Consider participating in the Open Source Security Foundation: Vulnerability Disclosures WG

### ISSUE THREAD

**Issue by JLLeitschuh** [TQRG/secom#4]
Hi!

I'm a member of the Open Source Security Foundation: Vulnerability Disclosures Working Group. I believe that the work around SECOM would be of great interest to the working group. I'd like to invite the SECOM team to participate in the working group. We have bi-weekly calls. The schedule can be found here:  https://openssf.org/getinvolved/

You can find out more about the working group here: https://github.com/ossf/wg-vulnerability-disclosures/blob/main/README.md

**Comment by sofiaoreis** [comment]
Hi, 

Thanks for sharing the details and the invite! I've shared the work with the best practices and vulnerability disclosure group (in the early stages of SECOM). I'm working on a tool to measure compliance and auto-generate commit messages. I think you found it already.

I've been planning to get more involved in the OpenSSF community for a while. But I did not know which working group to join, so I was waiting to have a bit more time to explore this. But I'll join the vulnerability disclosure one. I have an overlap this week, but I'll join the next meeting (April 5). Would that be ok for you?

**Comment by JLLeitschuh** [comment]
Perfect! Looking forward to seeing you there. There's also an AUTO Fix Special Interest Group (SIG) focused on automating vulnerability fixing at-scale that may also interest you. Those meetings are bi-weekly on Wednesdays at 4:00 PM EST
